/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gdut_base64_base64 */

#ifndef _Included_com_gdut_base64_base64
#define _Included_com_gdut_base64_base64
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gdut_base64_base64
 * Method:    base64encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdut_base64_base64_base64encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gdut_base64_base64
 * Method:    base64decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_gdut_base64_base64_base64decode
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
